### ISSUE TITLE
this.refs.editor.getDOMNode is not a function

### ISSUE THREAD

**Issue by shawnbissell** [sonyan/react-wysiwyg-editor#6]
Using React 15.0 I get this error from the emitChange function. It should be using React.findDOMNode(this.refs.editor) instead.

**Comment by sonyan** [comment]
fixed. Thanks for reporting bug!

**Comment by 957236298** [comment]
I use the React.findDOMNode(this.refs.editor) instead，but it still does not work,and why?How can I do?0.0

**Comment by sonyan** [comment]
I fix the issue with dom reference by using ref callback attribute. Check it out and see if it works for you.

**Comment by rodolfobandeira** [comment]
Just for future reference if someone lands on this page like me. Here I had to use ReactDOM here. So, `ReactDOM.findDOMNode(this.refs.foo)`

Very helpful though, Thanks!
